### ISSUE TITLE
Anyone reproduced the MountainCarContinuous-v0 results?

### ISSUE THREAD

**Issue by QiXuanWang** [ghliu/pytorch-ddpg#10]
I tried with same setting and the final stable average reward is close to 0, instead of 100. Is anyone tried this implementation doing getting expected values?

**Comment by QiXuanWang** [comment]
I do have some better results now after some rerun and tuning but still can't get the same results as author which is quite stable. My run begins to diverge after being stable for a while

**Comment by QiXuanWang** [comment]
Got consistent good results with ou_sigma=0.52, validate_episodes=200

**Comment by AlexZhaoZt** [comment]
I found that if you set ou_sigma too large, the reward will converge to -100. So, I think a good idea is to start from ou_sigma = 0.50, increase it, and if you see rewards converge to -100, decrease it, repeat (like doing a binary search). Using this method, I was able to find ou_sigma that gives stable result for any given seed.
