### ISSUE TITLE
Why MountainCarContinuous-v0 will converge to 0 ?

### ISSUE THREAD

**Issue by blackredscarf** [ghliu/pytorch-ddpg#5]
I used the code to train MountainCarContinuous-v0 directly.
But reward converges to 0.

![reward](https://i.loli.net/2018/08/21/5b7bdb4056964.png)

**Comment by QiXuanWang** [comment]
why this was closed? I got same results. Is it expected behavior?

**Comment by pengzhi1998** [comment]
I got similar results, but it shouldn't be. Because, if the robot reaches the goal, it will get a reward of 100 I think. What I'm curious about is that it seems the policy is not stable: sometimes the validation results remain high, sometimes remain around -99, sometimes remain around 0 ...
