### ISSUE TITLE
error in compute target q values

### ISSUE THREAD

**Issue by hejia-zhang** [ghliu/pytorch-ddpg#6]
```
        target_q_batch = to_tensor(reward_batch) + \
            self.discount*to_tensor(terminal_batch.astype(np.float))*next_q_values
```
I think it should be 
```
        target_q_batch = to_tensor(reward_batch) + \
            self.discount*to_tensor(1.0 - terminal_batch.astype(np.float))*next_q_values
```

**Comment by abalakrishna123** [comment]
yeah... that does seem like it would be the case

**Comment by songanz** [comment]
I think in the memory.py, he has:

        for e in experiences:
            state0_batch.append(e.state0)
            state1_batch.append(e.state1)
            reward_batch.append(e.reward)
            action_batch.append(e.action)
            terminal1_batch.append(0. if e.terminal1 else 1.)
